name: fax_app_cli
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  args: ^2.3.0
  hive: ^2.0.6
  http: ^0.13.4

dev_dependencies:
  build_runner: ^2.1.7
  hive_generator: ^1.1.2
  lints: ^1.0.1
